version: '3.7'

services:
  db:
    image: postgres:alpine
    container_name: sigeq_db
    ports:
      - 15432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=docker
      - POSTGRES_DB=sigeq_docker
    volumes:
      - "db:/var/lib/postgresql/data"
    networks:
      - sigeq_net

  api:
    build: .
    container_name: sigeq_api
    command: npm start
    restart: always
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - DB_HOST=sigeq_db
      - DB_USER=docker
      - DB_PASS=1234
      - DB_NAME=sigeq_docker
      - DB_DIALECT=postgres
      - DB_PORT=5432
      - API_SECRET=2cf8fd943de2a46c8babceb7da2d4e8e
  
    depends_on:
      - db
    networks:
      - sigeq_net

volumes:
  db: {}

networks:
  sigeq_net:
    driver: bridge

